// var restaurantTemp = [
//   {
//     name: "Sushi Bar Shu",
//     description: "Providing an omakase sushi experience while using fresh, seasonal seafood from Japan.",
//     phone: "+1 604-428-1868",
//     location: "8099 Granville Street",
//     photo: "http://www.makotojapanesebuffet.com/index_sushi_1_files/vlb_images5/23.jpg",
//     seats: 30,
//     id: 0,
//     reservationTime: [1900],
//     closedDays: ["Monday"],
//     maxParty: 3,
//   },
//   {
//     name: "Farmer's Apprentice",
//     description: "Located in Vancouver's South Granville - Kitsalino neighbourhood, Farmer's Apprentice is a reflection of BC's organic farmers, fishermen, and purveyors. The Pacific Northwest, vegetable forward menu seeks to support sustainable food systems, and is complimented by natural wine offerings, knowledgable staff and an approachable setting.",
//     phone: "+1 604-620-2070",
//     website: "https://farmersapprentice.ca/",
//     menu: 'https://farmersapprentice.ca/menu/',
//     location: "1535 West 6th Avenue",
//     photo: "https://farm3.staticflickr.com/2882/11302596064_7aac176bf6_b.jpg",
//     seats: 30,
//     id: 1,
//     reservationTime: [1100, 1115, 1130, 1145, 1200, 1215, 1230, 1245, 1300, 1315, 1330, 1345, 1730, 1745, 1800, 1915, 1930, 1945, 2000, 2100],
//     closedDays: ["Monday"],
//     maxParty: 6,
//   },
//   {
//     name: "Cacao",
//     description: "Our kitchen represents a progressive and fresh Latin American menu, created with a sinuous, steady hand and a focus on high quality, regional ingredients. Located within the charming and friendly neighbourhood of Kitsilano, Cacao is the very kind of neighbourhood corner post that becomes a favourite refuge after a long day, a place to gather and celebrate old friendships, new beginnings. A place to discover, or re-discover Latin American cuisine at its finest. Unpretentious. Surprising. Delightful. Lingering.",
//     phone: "+1 604-731-5370",
//     website: "https://cacao-vancouver.squarespace.com/",
//     menu: 'https://cacao-vancouver.squarespace.com/menu1/',
//     location: "1898 W 1st Ave",
//     photo: "http://www.nomss.com/wp-content/uploads/2016/11/Cacao-Restaurant-Vancouver-Chef-Jefferson-Alvarez-Instanomss-Nomss-Delicious-Food-Photography-Healthy-Travel-Lifestyle1195.jpg",
//     seats: 30,
//     id: 2,
//   },
//   {
//     name: "Poplar Grove Winery",
//     description: "At Poplar Grove, great wines are born from the courage to see what's possible and a passionate desire to work with our estate fruit to bring the Okanagan's full potential into each bottle. This is what we strive for each day.",
//     website: "https://www.poplargrove.ca/",
//     location: "425 Middle Bench Road North",
//     photo: "http://naramatabench.com/wp-content/uploads/2011/09/poplar-grove-winery-naramata.jpg",
//     seats: 30,
//     id: 3,
//     reservationTime: [1300, 1400, 1500],
//     closedDays: ["Monday", "Tuesday", "Wednsday", "Thursday"],
//     maxParty: 15
//   },
//   {
//     name: "Bauhaus Restaurant",
//     description: "Bauhaus sets a new standard for refined dining in Vancouver. Owned by German film director Uwe Boll, the award-winning restaurant is known for its modern take on German cuisine and attention to detail. The menu delicately balances European cuisine with west coast influences. The chef’s creativity can be seen, tasted and felt in each of their creations.",
//     phone: "+1 604-974-1147",
//     website: "https://bauhaus-restaurant.com/",
//     location: "1 W Cordova St",
//     photo: "https://resizer.otstatic.com/v2/photos/large/24929017.jpg",
//     seats: 30,
//     id: 4,
//   },
//   {
//     name: "Wildebeest",
//     description: "Wildebeest invites you to experience deliciously decadent yet simple country cooking. Explore a farm-to-table menu paired with a diverse selection of Old and New World wines and a carefully crafted cocktail list. Set in a refurbished 19th century building, the multi-level space offers a front house cocktail bar & lounge, open-concept kitchen, an inviting dining room with banquette seating, and an intimately-set private dining room.",
//     phone: "+1 250-764-0078",
//     website: "https://tantalus.ca/",
//     location: "120 West Hastings Street",
//     photo: "https://www.straight.com/files/gallery/adhoc/Wildebeast2_sm_0.jpg",
//     seats: 30,
//     id: 5,
//   },
// ]

export const viewRestaurantCards = (restaurants = [], action) => {
  return restaurants;
}